#!/bin/sh

stop_containers()  {
  docker compose --env-file "./env.config" down
  exit 0
}

# cd to script directory
cd -P -- "$(dirname -- "$0")" || {
  echo "Error: Could not change directory"
  exit 1
}

# Trap SIGINT and SIGTERM
trap stop_containers INT TERM

docker compose --env-file "./env.config" up

while true; do
  sleep 604800
done
