name: Build container-example application
on:
  workflow_dispatch:
  push:
    paths:
      - 'container-example/**'
      - '!container-example/README.md'
      - '.github/workflows/container-example.yml'
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - arch: armv7hf
            imagearch: arm32v7
            axis-os: 11.6.89
          - arch: aarch64
            imagearch: arm64v8
            axis-os: 11.6.89
    env:
      EXREPO: acap-native-examples
      EXNAME: container-example
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3

      - name: Build ${{ env.EXNAME }} application
        env:
          imagetag: ${{ env.EXREPO }}_${{ env.EXNAME }}:${{ matrix.arch }}
        run: |
          docker image rm -f $imagetag
          cd $EXNAME
          docker pull ${{ matrix.imagearch }}/alpine:3.14.0
          docker save -o alpine.tar ${{ matrix.imagearch }}/alpine:3.14.0
          docker build --no-cache --tag $imagetag .
          docker cp $(docker create $imagetag):/opt/app ./build
          cd ..
          docker image rm -f $imagetag
