name: Build container-example application
on:
  workflow_dispatch:
  push:
    paths:
      - 'container-example/**'
      - '!container-example/README.md'
      - '.github/workflows/container-example.yml'
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      EXREPO: acap-native-examples
      EXNAME: container-example
      EXDIR: acap/examples/$EXNAME
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2

      - name: Build ${{ env.EXNAME }} application
        env:
          imagetag: ${{ env.EXREPO }}_${{ env.EXNAME }}:1.0
        run: |
          docker image rm -f $imagetag
          cd $EXNAME
          docker pull arm32v7/alpine:3.14.0
          docker save -o alpine.tar arm32v7/alpine:3.14.0
          docker build --no-cache --tag $imagetag .
          docker cp $(docker create $imagetag):/opt/app ./build
          cd ..
          mkdir -p $EXDIR/build
          cp $EXNAME/build/*.eap $EXDIR/build/
          docker image rm -f $imagetag
