name: Build container-example application
on:
  push:
    paths:
      - 'container-example/**'
      - '!container-example/README.md'
      - '.github/workflows/container-example.yml'
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      EXREPO: acap-native-examples
      EXNAME: container-example
      EAPNAME: Container_Example
      EXDIR: acap/examples/$EXNAME
    steps:
      - uses: actions/checkout@v2

      - name: Build ${{ env.example }} application
        env:
          example: ${{ env.EXNAME }}
          imagetag: ${{ env.EXREPO }}_${{ env.EXNAME }}:1.0
          eapfile: ${{ env.EAPNAME }}_1_0_0_armv7hf.eap
        run: |
          docker image rm -f $imagetag
          cd $EXNAME
          docker pull arm32v7/alpine:3.14.0
          docker save -o alpine.tar arm32v7/alpine:3.14.0
          docker build --no-cache --tag $imagetag .
          docker cp $(docker create $imagetag):/opt/app ./build
          cd ..
          mkdir -p $EXDIR/build
          cp $EXNAME/build/$eapfile $EXDIR/build/$eapfile
          docker image rm -f $imagetag
