name: Build container example applications
on:
  push:
    paths:
      - "container-example/**"
      - ".github/workflows/container-example.yml"
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      RUN_FUNCTION_TEST: false
    steps:
      - uses: actions/checkout@v2

      - name: Login to dockerhub axis account
        run: docker login -u ${{ secrets.DOCKERHUB_USER }} --password ${{ secrets.DOCKERHUB_PASS }}

      - name: Build container example application
        run: |
          imagetag=container-example:1.0
          docker image rm -f $imagetag
          cd container-example
          docker pull arm32v7/alpine:3.14.0
          docker save -o alpine.tar arm32v7/alpine:3.14.0
          docker build --no-cache --tag $imagetag .
          docker cp $(docker create $imagetag .):/opt/app ./build
