name: Documentation checks

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - '**'

jobs:
  test:
    name: Documentation checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3

      - name: Verify that device URLs are consistent
        if: always()
        run: |
          .github/custom-linters/lint-device-urls.sh

      - name: Verify that there are no incorrect links to ACAP documentation
        if: always()
        run: |
          .github/custom-linters/lint-acap-documentation-urls.sh
