name: Example repository checks

on:
  workflow_dispatch:
  push:
  pull_request:
    branches:
      - '**'

jobs:
  test:
    name: Example repository checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3

      - name: Verify that all examples have expected structure
        if: always()
        run: |
          .github/custom-linters/lint-example-structure.sh
