name: Lint Renovate

on:
  workflow_dispatch:
  push:
    paths:
      - '.github/renovate.json'
      - '.github/workflows/linter-renovate-config.yml'

jobs:
  test:
    name: Lint Renovate config file
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - run: |
          docker run --rm \
            -v "$(pwd)"/.github/renovate.json:/usr/src/app/renovate.json \
            -e RENOVATE_CONFIG_FILE=/usr/src/app/renovate.json \
            -e LOG_LEVEL=debug \
            -t renovate/renovate:latest \
            renovate-config-validator
