name: Build metadata-broker applications
on:
  workflow_dispatch:
  push:
    paths:
      - 'metadata-broker/**'
      - '!metadata-broker/README.md'
      - '.github/workflows/metadata-broker.yml'
jobs:
  test-app:
    name: Test app
    runs-on: ubuntu-latest
    strategy:
      matrix:
        axis-os: ["11.10.61"]
        arch: ["armv7hf", "aarch64"]
    env:
      EXREPO: acap-native-examples
      EXNAME: metadata-broker
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3

      - name: Build ${{ env.example }} application
        env:
          example: consume-analytics-scene-description
          imagetag: ${{ env.EXREPO }}_consume-analytics-scene-description:${{ matrix.arch }}
        run: |
          docker image rm -f $imagetag
          cd $EXNAME/$example
          docker build --no-cache --tag $imagetag --build-arg ARCH=${{ matrix.arch }} .
          docker cp $(docker create $imagetag):/opt/app ./build
          cd ../..
          docker image rm -f $imagetag
