name: Build object-detection-cv25 application
on:
  workflow_dispatch:
  push:
    paths:
      - 'object-detection-cv25/**'
      - '!object-detection-cv25/README.md'
      - '.github/workflows/object-detection-cv25.yml'
jobs:
  test-app:
    name: Test app
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - arch: aarch64
            chip: cv25
            axis-os: 11.10.61
    env:
      EXREPO: acap-native-examples
      EXNAME: object-detection-cv25
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3

      - name: Build ${{ env.example }} application
        env:
          example: ${{ env.EXNAME }}
          imagetag: ${{ env.EXREPO }}_${{ env.EXNAME }}-${{ matrix.chip }}:${{ matrix.arch }}
        run: |
          docker image rm -f $imagetag
          cd $EXNAME
          docker build --no-cache --tag $imagetag .
          docker cp $(docker create $imagetag):/opt/app ./build_${{ matrix.chip }}
          cd ..
          docker image rm -f $imagetag
