name: Build object-detection Applications
on:
  push:
    paths:
      - "object-detection/**"
      - ".github/workflows/object-detection.yml"
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      RUN_FUNCTION_TEST: false
    steps:
      - uses: actions/checkout@v2

      - name: Login to dockerhub axis account
        run: docker login -u ${{ secrets.DOCKERHUB_USER }} --password ${{ secrets.DOCKERHUB_PASS }}

      - name: Configure axis proxy
        if: ${{ env.RUN_FUNCTION_TEST== 'true' }}
        run: |
          export DOCKER_CONFIG="$WORKSPACE/.docker"
          mkdir -p "$DOCKER_CONFIG"
          echo '{"proxies":{ "default":{"httpProxy": "http://wwwproxy.se.axis.com:3128", "httpsProxy": "http://wwwproxy.se.axis.com:3128"}}}' > "$DOCKER_CONFIG/config.json"

      - name: Build object-detection application
        run: |
          imagetag=object-detection-acap:1.0
          docker image rm -f $imagetag
          cd object-detection
          docker build --no-cache --tag $imagetag .
          docker cp $(docker create $imagetag):/opt/app ./build
          cd ..
          mkdir -p acap4-native/examples/object-detection/build
          cp object-detection/build/object_detection_app_1_0_0_armv7hf.eap acap4-native/examples/object-detection/build/object_detection_app_1_0_0_armv7hf.eap
          ls acap4-native/examples/object-detection/build/

      - name: Run functional tests
        if: ${{ env.RUN_FUNCTION_TEST== 'true' }}
        run: |
          export WORKSPACE=$(pwd)
          echo $WORKSPACE
          git clone "ssh://${{ secrets.GERRIT_SERVICE_USER }}@gittools.se.axis.com:29418/tests/atf/tart/recap.git"
          cd recap
          source /github-runner/github-runner/init/atf_init.sh
          ./test_starter.sh object_detection

      # Save functional test report as artifact
      - uses: actions/upload-artifact@master
        if: ${{ env.RUN_FUNCTION_TEST== 'true' }}
        with:
          name: Test report
          path: recap/recap/output/report.xml
