name: Build object-detection application
on:
  push:
    paths:
      - 'object-detection-cv25/**'
      - '!object-detection-cv25/README.md'
      - '.github/workflows/object-detection-cv25.yml'
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      EXREPO: acap-native-examples
      EXNAME: object-detection-cv25
      EAPNAME: object_detection
    steps:
      - uses: actions/checkout@v2

      - name: Build ${{ env.example }} application
        env:
          example: ${{ env.EXNAME }}-cv25
          imagetag: ${{ env.EXREPO }}_${{ env.EXNAME }}-cv25:1.0
          eapfile: ${{ env.EAPNAME }}_cv25_1_0_0_aarch64.eap
        run: |
          docker image rm -f $imagetag
          cd $EXNAME
          cp app/manifest.json.cv25 app/manifest.json
          docker build --no-cache --tag $imagetag .
          docker cp $(docker create $imagetag):/opt/app ./build_${{ matrix.chip }}
          cd ..
          docker image rm -f $imagetag


      # Save functional test report as artifact
      - uses: actions/upload-artifact@master
        with:
          name: Test report
          path: recap/recap/output/report.xml
