name: Build shell-script-example application
on:
  workflow_dispatch:
  push:
    paths:
      - 'shell-script-example/**'
      - '!shell-script-example/README.md'
      - '.github/workflows/shell-script-example.yml'
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: ["armv7hf", "aarch64"]
    env:
      EXREPO: acap-native-examples
      EXNAME: shell-script-example
      EXDIR: acap/examples/$EXNAME
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2

      - name: Build ${{ env.EXNAME }} application
        env:
          imagetag: ${{ env.EXREPO }}_${{ env.EXNAME }}:1.0
        run: |
          docker image rm -f $imagetag
          cd $EXNAME
          docker build --no-cache --tag $imagetag --build-arg ARCH=${{ matrix.arch }} .
          docker cp $(docker create $imagetag):/opt/app ./build
          cd ..
          docker image rm -f $imagetag
