name: Build tensorflow-to-larod Applications
on:
  push:
    paths:
      - "tensorflow-to-larod/**"
      - ".github/workflows/tensorflow-to-larod.yml"
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2

      - name: Build tensorflow-to-larod application
        run: |
          imagetag=tensorflow-to-larod-acap:1.0
          envname=tensorflow-to-larod
          docker image rm -f $imagetag
          export http_proxy=http://wwwproxy.se.axis.com:3128
          export https_proxy=http://wwwproxy.se.axis.com:3128
          export DOCKER_CONFIG="$WORKSPACE/.docker"
          mkdir -p "$DOCKER_CONFIG"
          echo '{"proxies":{ "default":{"httpProxy": "http://wwwproxy.se.axis.com:3128", "httpsProxy": "http://wwwproxy.se.axis.com:3128"}}}' > "$DOCKER_CONFIG/config.json"
          cd tensorflow-to-larod
          ./build_env.sh
          docker run -v /var/run/docker.sock:/var/run/docker.sock --network host --name tensorflow_env5 $envname /bin/bash ./build_acap.sh $imagetag
          docker cp tensorflow_env5:/env/build/tensorflow_to_larod_app_1_0_0_armv7hf.eap tensorflow_to_larod.eap
          docker stop tensorflow_env5
          docker rm tensorflow_env5
