name: Build vdo-larod applications
on:
  workflow_dispatch:
  push:
    paths:
      - 'vdo-larod/**'
      - '!vdo-larod/README.md'
      - '.github/workflows/vdo-larod.yml'
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - arch: armv7hf
            chip: cpu
            axis-os: 11.9.53
          - arch: armv7hf
            chip: edgetpu
            axis-os: 11.9.53
          - arch: aarch64
            chip: artpec8
            axis-os: 11.9.53
          - arch: aarch64
            chip: cv25
            axis-os: 11.9.53
    env:
      EXREPO: acap-native-examples
      EXNAME: vdo-larod
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3

      - name: Build ${{ env.example }} application
        env:
          example: ${{ env.EXNAME }}-${{ matrix.chip }}
          imagetag: ${{ env.EXREPO }}_${{ env.EXNAME }}_${{ matrix.chip }}:${{ matrix.arch }}
        run: |
          docker image rm -f $imagetag
          cd $EXNAME
          cp app/manifest.json.${{ matrix.chip }} app/manifest.json
          docker build --no-cache --build-arg CHIP=${{ matrix.chip }} --build-arg ARCH=${{ matrix.arch }} --tag $imagetag .
          docker cp $(docker create $imagetag):/opt/app ./build_${{ matrix.chip }}
          cd ..
          docker image rm -f $imagetag
