name: Build Web Server Applications
on:
  push:
    paths:
      - "web-server/**"
      - ".github/workflows/web-server.yml"
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      RUN_FUNCTION_TEST: false
    steps:
      - uses: actions/checkout@v2

      - name: Login to dockerhub axis account
        run: docker login -u ${{ secrets.DOCKERHUB_USER }} --password ${{ secrets.DOCKERHUB_PASS }}

      - name: Build web-server application
        run: |
          imagetag=web-server:1.0
          docker image rm -f $imagetag
          cd web-server
          docker build . --build-arg ARCH=armv7hf --build-arg http_proxy --build-arg https_proxy --no-cache --tag $imagetag
          docker cp $(docker create $imagetag):/opt/monkey/examples ./build
          cd ..
          mkdir -p acap4-native/examples/web-server/build
          cp web-server/build/monkey_1_0_0_armv7hf.eap acap4-native/examples/web-server/build/monkey_1_0_0_armv7hf.eap
          ls acap4-native/examples/web-server/build

      - name: Run functional tests
        if: ${{ env.RUN_FUNCTION_TEST== 'true' }}
        run: |
          export WORKSPACE=$(pwd)
          echo $WORKSPACE
          git clone "ssh://${{ secrets.GERRIT_SERVICE_USER }}@gittools.se.axis.com:29418/tests/atf/tart/recap.git"
          cd recap
          source /github-runner/github-runner/init/atf_init.sh
          ./test_starter.sh monkey
          ls recap/output

      # Save functional test report as artifact
      - uses: actions/upload-artifact@master
        if: ${{ env.RUN_FUNCTION_TEST== 'true' }}
        with:
          name: Test report
          path: recap/recap/output/report.xml
